apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management-service
spec:
  selector:
    app: user-management-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
spec:
  selector:
    matchLabels:
      app: user-management-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      name: user-management-service
      labels:
        app: user-management-service
    spec:
      containers:
        - name: user-management-service
          image: registry.gitlab.com/vyper-global/user-management-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/user-service/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/v1/user-service/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 600Mi
      imagePullSecrets:
        - name: regcred