# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: user-management-service ci cd flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SI_CLUSTER: sales-inventory
  SI_ZONE: us-central1-c
  DEPLOYEMENT_NAME: github-action-sales-inventory-deployement

jobs:
  build:
    env:
      ACTION_TOKEN: ${{secrets.ACTION_TOKEN}}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --settings settings.xml clean install -DskipTests

      - names: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}

      - names: Get Sales Inventroy Cluster Credintials
        run: gcloud container cluster get-credintials "$SI_CLUSTER" --zone "SI_ZONE"

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: janithsenanyaka/user-management-service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



